In [33]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')

In [47]:
dataset=pd.read_csv('E:\\DATA SCIENCE\\all csv files\\melb_data.csv')
dataset

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra,-37.79960,144.99840,Northern Metropolitan,4019.0
1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra,-37.80790,144.99340,Northern Metropolitan,4019.0
2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra,-37.80930,144.99440,Northern Metropolitan,4019.0
3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,...,2.0,1.0,94.0,NaN,NaN,Yarra,-37.79690,144.99690,Northern Metropolitan,4019.0
4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,1.0,2.0,120.0,142.0,2014.0,Yarra,-37.80720,144.99410,Northern Metropolitan,4019.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13575,Wheelers Hill,12 Strada Cr,4,h,1245000.0,S,Barry,26/08/2017,16.7,3150.0,...,2.0,2.0,652.0,NaN,1981.0,NaN,-37.90562,145.16761,South-Eastern Metropolitan,7392.0
13576,Williamstown,77 Merrett Dr,3,h,1031000.0,SP,Williams,26/08/2017,6.8,3016.0,...,2.0,2.0,333.0,133.0,1995.0,NaN,-37.85927,144.87904,Western Metropolitan,6380.0
13577,Williamstown,83 Power St,3,h,1170000.0,S,Raine,26/08/2017,6.8,3016.0,...,2.0,4.0,436.0,NaN,1997.0,NaN,-37.85274,144.88738,Western Metropolitan,6380.0
13578,Williamstown,96 Verdon St,4,h,2500000.0,PI,Sweeney,26/08/2017,6.8,3016.0,...,1.0,5.0,866.0,157.0,1920.0,NaN,-37.85908,144.89299,Western Metropolitan,6380.0
13579,Yarraville,6 Agnes St,4,h,1285000.0,SP,Village,26/08/2017,6.3,3013.0,...,1.0,1.0,362.0,112.0,1920.0,NaN,-37.81188,144.88449,Western Metropolitan,6543.0

In [48]:
dataset.nunique()

Suburb             314
Address          13378
Rooms                9
Type                 3
Price             2204
Method               5
SellerG            268
Date                58
Distance           202
Postcode           198
Bedroom2            12
Bathroom             9
Car                 11
Landsize          1448
BuildingArea       602
YearBuilt          144
CouncilArea         33
Lattitude         6503
Longtitude        7063
Regionname           8
Propertycount      311
dtype: int64

In [49]:
dataset.shape

(13580, 21)

In [50]:
dataset.columns

Index(['Suburb', 'Address', 'Rooms', 'Type', 'Price', 'Method', 'SellerG',
       'Date', 'Distance', 'Postcode', 'Bedroom2', 'Bathroom', 'Car',
       'Landsize', 'BuildingArea', 'YearBuilt', 'CouncilArea', 'Lattitude',
       'Longtitude', 'Regionname', 'Propertycount'],
      dtype='object')

In [51]:
col_use=['Suburb','Rooms','Type','Method','SellerG','Regionname','Propertycount','Distance',
        'CouncilArea','Bedroom2','Bathroom','Car','Landsize','BuildingArea','Price']
df=dataset[col_use]
df

,Suburb,Rooms,Type,Method,SellerG,Regionname,Propertycount,Distance,CouncilArea,Bedroom2,Bathroom,Car,Landsize,BuildingArea,Price
0,Abbotsford,2,h,S,Biggin,Northern Metropolitan,4019.0,2.5,Yarra,2.0,1.0,1.0,202.0,NaN,1480000.0
1,Abbotsford,2,h,S,Biggin,Northern Metropolitan,4019.0,2.5,Yarra,2.0,1.0,0.0,156.0,79.0,1035000.0
2,Abbotsford,3,h,SP,Biggin,Northern Metropolitan,4019.0,2.5,Yarra,3.0,2.0,0.0,134.0,150.0,1465000.0
3,Abbotsford,3,h,PI,Biggin,Northern Metropolitan,4019.0,2.5,Yarra,3.0,2.0,1.0,94.0,NaN,850000.0
4,Abbotsford,4,h,VB,Nelson,Northern Metropolitan,4019.0,2.5,Yarra,3.0,1.0,2.0,120.0,142.0,1600000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13575,Wheelers Hill,4,h,S,Barry,South-Eastern Metropolitan,7392.0,16.7,NaN,4.0,2.0,2.0,652.0,NaN,1245000.0
13576,Williamstown,3,h,SP,Williams,Western Metropolitan,6380.0,6.8,NaN,3.0,2.0,2.0,333.0,133.0,1031000.0
13577,Williamstown,3,h,S,Raine,Western Metropolitan,6380.0,6.8,NaN,3.0,2.0,4.0,436.0,NaN,1170000.0
13578,Williamstown,4,h,PI,Sweeney,Western Metropolitan,6380.0,6.8,NaN,4.0,1.0,5.0,866.0,157.0,2500000.0
13579,Yarraville,4,h,SP,Village,Western Metropolitan,6543.0,6.3,NaN,4.0,1.0,1.0,362.0,112.0,1285000.0

In [52]:
df.isnull().sum() #OR dataset.isna().sum()

Suburb              0
Rooms               0
Type                0
Method              0
SellerG             0
Regionname          0
Propertycount       0
Distance            0
CouncilArea      1369
Bedroom2            0
Bathroom            0
Car                62
Landsize            0
BuildingArea     6450
Price               0
dtype: int64

In [53]:
df.columns

Index(['Suburb', 'Rooms', 'Type', 'Method', 'SellerG', 'Regionname',
       'Propertycount', 'Distance', 'CouncilArea', 'Bedroom2', 'Bathroom',
       'Car', 'Landsize', 'BuildingArea', 'Price'],
      dtype='object')

In [54]:
df['Car']=df.Car.fillna(df.Car.median())
df['BuildingArea']=df.BuildingArea.fillna(df.BuildingArea.median())
df

,Suburb,Rooms,Type,Method,SellerG,Regionname,Propertycount,Distance,CouncilArea,Bedroom2,Bathroom,Car,Landsize,BuildingArea,Price
0,Abbotsford,2,h,S,Biggin,Northern Metropolitan,4019.0,2.5,Yarra,2.0,1.0,1.0,202.0,126.0,1480000.0
1,Abbotsford,2,h,S,Biggin,Northern Metropolitan,4019.0,2.5,Yarra,2.0,1.0,0.0,156.0,79.0,1035000.0
2,Abbotsford,3,h,SP,Biggin,Northern Metropolitan,4019.0,2.5,Yarra,3.0,2.0,0.0,134.0,150.0,1465000.0
3,Abbotsford,3,h,PI,Biggin,Northern Metropolitan,4019.0,2.5,Yarra,3.0,2.0,1.0,94.0,126.0,850000.0
4,Abbotsford,4,h,VB,Nelson,Northern Metropolitan,4019.0,2.5,Yarra,3.0,1.0,2.0,120.0,142.0,1600000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13575,Wheelers Hill,4,h,S,Barry,South-Eastern Metropolitan,7392.0,16.7,NaN,4.0,2.0,2.0,652.0,126.0,1245000.0
13576,Williamstown,3,h,SP,Williams,Western Metropolitan,6380.0,6.8,NaN,3.0,2.0,2.0,333.0,133.0,1031000.0
13577,Williamstown,3,h,S,Raine,Western Metropolitan,6380.0,6.8,NaN,3.0,2.0,4.0,436.0,126.0,1170000.0
13578,Williamstown,4,h,PI,Sweeney,Western Metropolitan,6380.0,6.8,NaN,4.0,1.0,5.0,866.0,157.0,2500000.0
13579,Yarraville,4,h,SP,Village,Western Metropolitan,6543.0,6.3,NaN,4.0,1.0,1.0,362.0,112.0,1285000.0

In [55]:
df.isnull().sum()

Suburb              0
Rooms               0
Type                0
Method              0
SellerG             0
Regionname          0
Propertycount       0
Distance            0
CouncilArea      1369
Bedroom2            0
Bathroom            0
Car                 0
Landsize            0
BuildingArea        0
Price               0
dtype: int64

In [56]:
df.fillna(method='pad')

,Suburb,Rooms,Type,Method,SellerG,Regionname,Propertycount,Distance,CouncilArea,Bedroom2,Bathroom,Car,Landsize,BuildingArea,Price
0,Abbotsford,2,h,S,Biggin,Northern Metropolitan,4019.0,2.5,Yarra,2.0,1.0,1.0,202.0,126.0,1480000.0
1,Abbotsford,2,h,S,Biggin,Northern Metropolitan,4019.0,2.5,Yarra,2.0,1.0,0.0,156.0,79.0,1035000.0
2,Abbotsford,3,h,SP,Biggin,Northern Metropolitan,4019.0,2.5,Yarra,3.0,2.0,0.0,134.0,150.0,1465000.0
3,Abbotsford,3,h,PI,Biggin,Northern Metropolitan,4019.0,2.5,Yarra,3.0,2.0,1.0,94.0,126.0,850000.0
4,Abbotsford,4,h,VB,Nelson,Northern Metropolitan,4019.0,2.5,Yarra,3.0,1.0,2.0,120.0,142.0,1600000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13575,Wheelers Hill,4,h,S,Barry,South-Eastern Metropolitan,7392.0,16.7,Maribyrnong,4.0,2.0,2.0,652.0,126.0,1245000.0
13576,Williamstown,3,h,SP,Williams,Western Metropolitan,6380.0,6.8,Maribyrnong,3.0,2.0,2.0,333.0,133.0,1031000.0
13577,Williamstown,3,h,S,Raine,Western Metropolitan,6380.0,6.8,Maribyrnong,3.0,2.0,4.0,436.0,126.0,1170000.0
13578,Williamstown,4,h,PI,Sweeney,Western Metropolitan,6380.0,6.8,Maribyrnong,4.0,1.0,5.0,866.0,157.0,2500000.0
13579,Yarraville,4,h,SP,Village,Western Metropolitan,6543.0,6.3,Maribyrnong,4.0,1.0,1.0,362.0,112.0,1285000.0

In [57]:
df.isnull().sum()

Suburb              0
Rooms               0
Type                0
Method              0
SellerG             0
Regionname          0
Propertycount       0
Distance            0
CouncilArea      1369
Bedroom2            0
Bathroom            0
Car                 0
Landsize            0
BuildingArea        0
Price               0
dtype: int64

In [58]:
df['CouncilArea'].value_counts()

Moreland             1163
Boroondara           1160
Moonee Valley         997
Darebin               934
Glen Eira             848
Stonnington           719
Maribyrnong           692
Yarra                 647
Port Phillip          628
Banyule               594
Bayside               489
Melbourne             470
Hobsons Bay           434
Brimbank              424
Monash                333
Manningham            311
Whitehorse            304
Kingston              207
Whittlesea            167
Hume                  164
Wyndham                86
Knox                   80
Maroondah              80
Melton                 66
Frankston              53
Greater Dandenong      52
Casey                  38
Nillumbik              36
Yarra Ranges           18
Cardinia                8
Macedon Ranges          7
Moorabool               1
Unavailable             1
Name: CouncilArea, dtype: int64

In [62]:
newdf=df.fillna({'CouncilArea':'Macedon Ranges'})
newdf

,Suburb,Rooms,Type,Method,SellerG,Regionname,Propertycount,Distance,CouncilArea,Bedroom2,Bathroom,Car,Landsize,BuildingArea,Price
0,Abbotsford,2,h,S,Biggin,Northern Metropolitan,4019.0,2.5,Yarra,2.0,1.0,1.0,202.0,126.0,1480000.0
1,Abbotsford,2,h,S,Biggin,Northern Metropolitan,4019.0,2.5,Yarra,2.0,1.0,0.0,156.0,79.0,1035000.0
2,Abbotsford,3,h,SP,Biggin,Northern Metropolitan,4019.0,2.5,Yarra,3.0,2.0,0.0,134.0,150.0,1465000.0
3,Abbotsford,3,h,PI,Biggin,Northern Metropolitan,4019.0,2.5,Yarra,3.0,2.0,1.0,94.0,126.0,850000.0
4,Abbotsford,4,h,VB,Nelson,Northern Metropolitan,4019.0,2.5,Yarra,3.0,1.0,2.0,120.0,142.0,1600000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13575,Wheelers Hill,4,h,S,Barry,South-Eastern Metropolitan,7392.0,16.7,Macedon Ranges,4.0,2.0,2.0,652.0,126.0,1245000.0
13576,Williamstown,3,h,SP,Williams,Western Metropolitan,6380.0,6.8,Macedon Ranges,3.0,2.0,2.0,333.0,133.0,1031000.0
13577,Williamstown,3,h,S,Raine,Western Metropolitan,6380.0,6.8,Macedon Ranges,3.0,2.0,4.0,436.0,126.0,1170000.0
13578,Williamstown,4,h,PI,Sweeney,Western Metropolitan,6380.0,6.8,Macedon Ranges,4.0,1.0,5.0,866.0,157.0,2500000.0
13579,Yarraville,4,h,SP,Village,Western Metropolitan,6543.0,6.3,Macedon Ranges,4.0,1.0,1.0,362.0,112.0,1285000.0

In [63]:
newdf.isnull().sum()

Suburb           0
Rooms            0
Type             0
Method           0
SellerG          0
Regionname       0
Propertycount    0
Distance         0
CouncilArea      0
Bedroom2         0
Bathroom         0
Car              0
Landsize         0
BuildingArea     0
Price            0
dtype: int64

In [64]:
newdf.shape

(13580, 15)

In [65]:
newdf=pd.get_dummies(newdf,drop_first=True)
newdf

,Rooms,Propertycount,Distance,Bedroom2,Bathroom,Car,Landsize,BuildingArea,Price,Suburb_Aberfeldie,...,CouncilArea_Moreland,CouncilArea_Nillumbik,CouncilArea_Port Phillip,CouncilArea_Stonnington,CouncilArea_Unavailable,CouncilArea_Whitehorse,CouncilArea_Whittlesea,CouncilArea_Wyndham,CouncilArea_Yarra,CouncilArea_Yarra Ranges
0,2,4019.0,2.5,2.0,1.0,1.0,202.0,126.0,1480000.0,0,...,0,0,0,0,0,0,0,0,1,0
1,2,4019.0,2.5,2.0,1.0,0.0,156.0,79.0,1035000.0,0,...,0,0,0,0,0,0,0,0,1,0
2,3,4019.0,2.5,3.0,2.0,0.0,134.0,150.0,1465000.0,0,...,0,0,0,0,0,0,0,0,1,0
3,3,4019.0,2.5,3.0,2.0,1.0,94.0,126.0,850000.0,0,...,0,0,0,0,0,0,0,0,1,0
4,4,4019.0,2.5,3.0,1.0,2.0,120.0,142.0,1600000.0,0,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13575,4,7392.0,16.7,4.0,2.0,2.0,652.0,126.0,1245000.0,0,...,0,0,0,0,0,0,0,0,0,0
13576,3,6380.0,6.8,3.0,2.0,2.0,333.0,133.0,1031000.0,0,...,0,0,0,0,0,0,0,0,0,0
13577,3,6380.0,6.8,3.0,2.0,4.0,436.0,126.0,1170000.0,0,...,0,0,0,0,0,0,0,0,0,0
13578,4,6380.0,6.8,4.0,1.0,5.0,866.0,157.0,2500000.0,0,...,0,0,0,0,0,0,0,0,0,0
13579,4,6543.0,6.3,4.0,1.0,1.0,362.0,112.0,1285000.0,0,...,0,0,0,0,0,0,0,0,0,0

In [66]:
x=newdf.drop(['Price'],axis=1)
y=newdf[['Price']]

In [71]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=2)

In [72]:
from sklearn.linear_model import LinearRegression
reg=LinearRegression().fit(x_train,y_train)

In [73]:
reg.score(x_train,y_train)

0.7203906972792324

In [74]:
reg.score(x_test,y_test)

-108626036581.75023

# Lasso(L1)Regression

In [89]:
from sklearn import linear_model
lasso_reg=linear_model.Lasso(alpha=0.1,max_iter=1000,tol=0.1)
lasso_reg.fit(x_train,y_train)

Lasso(alpha=0.1, tol=0.1)

In [90]:
lasso_reg.score(x_train,y_train)

0.7203903957450305

In [91]:
lasso_reg.score(x_test,y_test)

0.07203406463337247

# Ridge(L2)Regression

In [95]:
from sklearn.linear_model import Ridge
ridge_reg=Ridge(alpha=0.1,max_iter=1000,tol=0.1)
ridge_reg.fit(x_train,y_train)

Ridge(alpha=0.1, max_iter=1000, tol=0.1)

In [96]:
ridge_reg.score(x_train,y_train)

0.720343883668686

In [97]:
ridge_reg.score(x_test,y_test)

0.06300477794061843